# Add post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "message": "This is a test post",
    "sender": "romco@example.com"
}

###

# Get all posts
GET http://localhost:3000/posts

###

# Get a single post by ID
GET http://localhost:3000/posts/67403fcbdb2822647397998e

###

# Get posts by sender
GET http://localhost:3000/posts?sender=romco@example.com

###

# Update a post
PUT http://localhost:3000/posts/67403fcbdb2822647397998e
Content-Type: application/json

{
    "message": "This is a different post"
}

###

# Add comment to a post

POST http://localhost:3000/comments
Content-Type: application/json

{
  "post": "67403fcbdb2822647397998e",
  "message": "This is a test comment 2",
  "sender": "romco@example.com"
}

###

# Get all comments
GET http://localhost:3000/comments

###
# Get comments for a specific post
GET http://localhost:3000/comments?post=67403fcbdb2822647397998e

###
# Get comments by a specific sender
GET http://localhost:3000/comments?sender=romco@example.com

###
# Get a single comment by ID
GET http://localhost:3000/comments/674055e9bc95c678be7b30df

###
# Update a comment
PUT http://localhost:3000/comments/674055e9bc95c678be7b30df
Content-Type: application/json

{
  "message": "This is an updated comment 2"
}

###
# Delete a comment
DELETE http://localhost:3000/comments/674055e9bc95c678be7b30df